# Custom Language File for Launcher Customizer

[ejs.app]
title = "MineSquare launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/djl987645/MineSquareLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xD6x3snQ"

[ejs.settings]
sourceGithubLink = "https://github.com/djl987645/MineSquareLauncher"
supportLink = "https://github.com/djl987645/MineSquareLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MineSquare!"
welcomeDescription = "경기대 마인크래프트 서버인 마인스퀘어에 어서오세요!"
welcomeDescCTA = "마크에서도 경기대 캠퍼스 라이프를 즐기세요!"
