name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      # macOS용 dmg 파일에 Sigstore 서명
      - name: Sign macOS DMG
        if: matrix.os == 'macos-latest'
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: dist/MineSquare Launcher-setup-*.dmg
          release-signing-artifacts: true

      # Windows용 exe 파일에 Sigstore 서명
      - name: Sign Windows EXE
        if: matrix.os == 'windows-latest'
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: dist/MineSquare Launcher-setup-*.exe
          release-signing-artifacts: true

      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: MineSquare_Launcher_macOS
          path: |
            dist/latest-mac.yml
            dist/MineSquare Launcher-setup-*.dmg

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: MineSquare_Launcher_Windows
          path: |
            dist/latest.yml
            dist/MineSquare Launcher-setup-*.exe
