name: Commit distribution.json

on:
  push:
    paths:
      - 'json/distributoin.json'

jobs:
  commit-distribution-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete cached distribution.json
        run: |
          git config --global user.email "djl987645@gmail.com"
          git config --global user.name "djl987645"
          git rm --cached json/distribution.json
          git commit -m "Remove cached distribution.json"
          git push origin master # master 브랜치로 푸시합니다.
          
      - name: Add distribution.json and commit
        run: |
          git config --global user.email "djl987645@gmail.com"
          git config --global user.name "djl987645"
          echo "New content" > distribution.json # distribution.json 파일에 새로운 내용을 추가하세요.
          git add json/distribution.json
          git commit -m "Add new content to distribution.json"
          git push origin master # master 브랜치로 푸시합니다.

